int16 modeRuning

string lbv_name_agv
string lbv_ip
string lbv_battery
string lbv_date

string lbv_device
string lbv_frameWork
string lbv_detailError

string lbv_x
string lbv_y
string lbv_zd

string lbv_ex
string lbv_ey
string lbv_eg

string lbv_idGoal

string lbv_ping
string lbv_ros
string lbv_velLeft
string lbv_velRight

string lbv_mode
string lbv_detect
string lbv_job
string lbv_load

string lbv_job1
string lbv_point0
string lbv_point1
string lbv_point2
string lbv_point3
string lbv_point4
string lbv_job2
string lbv_pointFinal
string lbv_plan

string lbv_idLocal
string lbv_idGlobal
string lbv_distance
string lbv_quality

string[] cb_listError
string[] cb_listWarn