bool bt_cancelMission
bool bt_passHand
bool bt_passAuto	
bool bt_clearError

bool bt_spk_on
bool bt_spk_off

bool bt_chg_on
bool bt_chg_off

bool bt_lift_up
bool bt_lift_down

bool bt_forwards
bool bt_backwards
bool bt_rotation_left
bool bt_rotation_right
bool bt_stop

int16 vs_speed
bool bt_resetFrameWork
bool bt_disableBrake

bool bt_tryTarget_start
bool bt_tryTarget_stop
bool bt_tryTarget_reset
bool ck_tryTarget_safety

float64 tryTarget_x
float64 tryTarget_y
float64 tryTarget_r
float64 tryTarget_d
