bool bt_cancelMission
bool bt_passHand
bool bt_passAuto	
bool bt_clearError

bool bt_hide

bool bt_spk_on
bool bt_spk_off

bool bt_chg_on
bool bt_chg_off

int16 bt_lift

bool bt_forwards
bool bt_backwards
bool bt_rotation_left
bool bt_rotation_right
bool bt_stop

bool bt_disableBrake
int16 soundtype
int16 ledtype
bool bt_resetFrameWork
bool bt_remote
int16 vs_speed
bool bt_setting

bool bt_coorAverage
bool bt_disPointA
bool bt_disPointB
bool bt_hideSetting

bool bt_tryTarget_start
bool bt_tryTarget_stop
bool bt_tryTarget_reset
bool ck_tryTarget_safety

float64 tryTarget_x
float64 tryTarget_y
float64 tryTarget_r
float64 tryTarget_d
float64[] list_special_x
float64[] list_special_y
float64[] list_special_z

int8 bt_wifi
