bool bt_cancelMission
bool bt_passHand
bool bt_passAuto	
bool bt_clearError

bool bt_tryTarget

bool bt_spk_on
bool bt_spk_off

bool bt_chg_on
bool bt_chg_off

bool bt_lift_up
bool bt_lift_down

bool bt_forwards
bool bt_backwards
bool bt_rotation_left
bool bt_rotation_right
bool bt_stop

int16 vs_speed
bool bt_resetFrameWork
bool bt_free

bool tryTarget_start
bool tryTarget_stop
bool tryTarget_reset
bool tryTarget_x
bool tryTarget_y
bool tryTarget_r
bool tryTarget_d