bool bt_pass_auto
bool bt_pass_hand
bool bt_cancel_mission
bool bt_setting
bool bt_clear_error

int16 bt_move_hand

bool bt_coor_average
bool bt_dis_point_a
bool bt_dis_point_b

bool bt_hide_setting

bool bt_set_pose
bool bt_speaker
bool bt_charger
bool bt_lifter

bool bt_auxiliary_lights

int16 vs_speed
bool ck_remote
bool ck_magline

bool bt_reset_framework

int16 sound_type
int16 led_type

int16 bt_confirm