int8 bt_pass_auto
int8 bt_pass_hand
int8 bt_cancel_mission
int8 bt_setting
int8 bt_clear_error

int8 bt_movehand

int8 bt_coor_average
int8 bt_dis_point_a
int8 bt_dis_point_b

int8 bt_hide_setting

int8 bt_setpose
int8 bt_speaker
int8 bt_charger
int16 bt_lifter

int8 bt_disable_brake

int16 vs_speed
int8 ck_remote
int8 ck_magline

int8 bt_reset_framework
int8 bt_confirm

int16 soundtype
int16 ledtype

int8 bt_dir
