uint64 rfid_last_code # rfid đọc đc ở thời điểm trc
uint64 rfid_code # rfid đọc đc ở thời điểm hiện tại
int32 direction # hướng hiện tại của AGV
int64 offset # tt lagv
int32 tag # tt lagv
int32 battery # tt lagv
int32 status # tt lagv
int32 mode # tt lagv
int32 task_status # tt lagv
int32 error_device # tt lagv
int32 error_moving # tt lagv
int32 error_perform # tt lagv
int32[] list_error # tt lagv
int32 process # tt lagv